language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libpng12-dev
      - libgtk2.0-dev
      - zlib1g-dev
before_script:
  - mkdir build
  - cd build
  - curl -L https://github.com/Wargus/stratagus/archive/master.zip -O master.zip || true
  - unzip master.zip
  - cmake -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR="$PWD/stratagus-master/gameheaders" ..
script: make
