language: cpp
compiler:
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libpng12-dev
      - libgtk2.0-dev
      - zlib1g-dev
env:
  global:
    secure: "FK2YokpeWWUd1gpPCgPTcH7sbYw1Wam8ImeR1Xjf3mC8VaISOzXvF1DTmHjOKqrIP+xlgsA8XuI9xLU8U1vdFMRA2XfC+a0tozRAknzhkBHC61ysfbxwnv072CBtG6rg6Qw+zvNEixUo7bCMLlPaS8h/UHC7l/1diXBndw435lEpngiIDgiCG2REXpLPkRyIJ9G1VrhTKBWtMqNs4na9glgxLao+AYE1gimLaqq7qraXSP8339hWU0PFGqBnqC/TG5dKJCbciMAqdjs/QPxqnvJR2Eqqpd0Yb+nNn9aRq715cT8Rlck981YOowpHrfer+9YhEimFRJyY8McjQcvRWGT9mCDiwulB/WrveesktWauOGyKJJXMidragfDMELjsShYjsCGUJOmM5MNBWbfkr1iT0Mf2H/sd9Ey2RgUzFAbELBghGdEVisbMeXrKIJhUAzynNNPQRNPJB4yJjXYF6tYIZ/kEYqR4C8ohYq+JzYkEVhl4VngApWJKtZZmtB0t0ND6VcqFDMrBf2L3uyvJkgLDlx6iLDQ8ZNOgWCtAGNOEKZhv/d9fG346nc9Q/RcEZU8jJlJSI0TOgrgCBLNWHNFMrBqSMMj0mngT2jOkKRV+rFlB5Gq9rwCDhp0cev+Ce+1WOYTkl7M+1pABLgsJP1WvGV2MpPxtEpvjaYKwEKM="
before_script:
  - mkdir build
  - cd build
  - git clone https://github.com/ladislav-zezula/StormLib.git
  - cd StormLib
  - "if [ $TRAVIS_OS_NAME == linux ]; then \
        make -f Makefile.linux;
        export STORMLIB=\"$PWD/libStorm.a\";
    fi"
  - "if [ $TRAVIS_OS_NAME == osx ]; then \
        make -f Makefile.mac;
        export STORMLIB=\"$PWD/StormLib.a\";
        find . -name \"*.o\" | xargs ar rcs \"$PWD/StormLib.a\";
        ls /usr/local/lib/;
    fi"
  - cd ..
  - curl -L https://github.com/Wargus/stratagus/archive/master.zip -O master.zip || true
  - unzip master.zip
  - cmake $EXTRA_CMAKE_FLAGS -DSTORMLIB_INCLUDE_DIR="$PWD/StormLib/src" -DSTORMLIB_LIBRARY="$STORMLIB" -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR="$PWD/stratagus-master/gameheaders" ..
script: make
after_success:
  - "if [ $TRAVIS_OS_NAME == osx ]; then \
        if [ $TRAVIS_REPO_SLUG == Wargus/wargus -a \
             $TRAVIS_BRANCH == master -a \
             $TRAVIS_PULL_REQUEST == 'false' ]; then \
           cd $TRAVIS_BUILD_DIR;
           git clone https://${GH_TOKEN}@github.com/Wargus/stratagus.wiki.git;
           export STRATAGUS=$(pwd)/stratagus.wiki/$TRAVIS_OS_NAME/stratagus;
           mac/bundle.sh;
           tar czvf Wargus.app.tar.gz mac/Wargus.app;
           cp Wargus.app.tar.gz stratagus.wiki/$TRAVIS_OS_NAME/;
           cd stratagus.wiki/;
           git config --global user.email \"travis-ci@travis.org\";
           git config --global user.name \"Travis CI\";
           git add $TRAVIS_OS_NAME/Wargus.app.tar.gz;
           git commit --amend -C HEAD;
           git push -fq origin master;
           cd ..;
        fi;
    fi"
